# Generated by Django 5.0.4 on 2024-04-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_placeorder_cart_placeorder_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='payement',
            new_name='payment',
        ),
    ]
