# Generated by Django 5.0.4 on 2024-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_payement_placeorder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='cancel_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
