# Generated by Django 5.0.4 on 2024-04-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_placeorder_cancel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='cancel_order',
        ),
    ]
