# Generated by Django 5.0.4 on 2024-04-27 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_placeorder_cancel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='cart',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='products',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
